spring:
  datasource:
    url: jdbc:mysql://localhost:3306/andalusia?autoReconnect=true&useSSL=false
    username: andalusia
    password: andalusia
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 11000
